<a href="https://colab.research.google.com/github/yot85/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__


'1.21.6'

In [4]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__'

In [ ]:
help(np.array)

## 1D array

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [13]:
x = np.array([1.3, 2.3, 3.4])
print(x)

[1.3 2.3 3.4]


In [14]:
x.dtype

dtype('float64')

### 2D Array

In [16]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [17]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [19]:
x.size

4

In [21]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [22]:
x.shape

(2, 3)

## 3D Array

In [26]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[4, 2, 1],
      [1,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[4, 2, 1],
        [1, 3, 2]]])

In [27]:
x.ndim

3

In [28]:
x.shape

(3, 2, 3)

# Typy danych

In [29]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [30]:
A = np.array([1.0, 2.1, 3.2])
A.dtype

dtype('float64')

In [31]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [32]:
A

array([1., 2., 3.])

In [33]:
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [34]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [35]:
A = np.array([1.0, 2.1, 3.2], dtype='int')
A.dtype

dtype('int64')

In [36]:
A

array([1, 2, 3])

In [37]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [39]:
A = np.array([24, 128, 256], dtype=np.int8)
A.dtype

dtype('int8')

# Tworzenie tablic

In [41]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [43]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
np.ones(shape=(5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [45]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [48]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [50]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [53]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

'''linspace tworzy tablice o ilości elementów równo rozłożonych w danym przedziale liczb'''

In [56]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

-1 oznacza że nie chcemy sami delfiniować ilości kolumn, chcemy aby NumPy sam dobrał odpowiednią ilość kolumn dla 3 wierszy i 15 elementów w tablicy

In [61]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Podstawowe operacje na tablicach

In [62]:
A = np.array([1, 2, 3, 4])
B = np.array([2, -1, 3,5])
print(A)
print(B)

[1 2 3 4]
[ 2 -1  3  5]


In [63]:
A + B

array([3, 1, 6, 9])

In [64]:
A - B

array([-1,  3,  0, -1])

In [65]:
A * B

array([ 2, -2,  9, 20])

In [66]:
A / B

array([ 0.5, -2. ,  1. ,  0.8])

In [67]:
A + 3

array([4, 5, 6, 7])

In [68]:
A -3

array([-2, -1,  0,  1])

In [69]:
2*A

array([2, 4, 6, 8])

In [70]:
A + 3*B

array([ 7, -1, 12, 19])

In [71]:
np.add(A,B)

array([3, 1, 6, 9])

In [72]:
np.subtract(A,B)

array([-1,  3,  0, -1])

In [73]:
np.multiply(A,B)

array([ 2, -2,  9, 20])

In [74]:
np.divide(A,B)

array([ 0.5, -2. ,  1. ,  0.8])