<a href="https://colab.research.google.com/github/yot85/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__


'1.21.6'

In [4]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__'

In [ ]:
help(np.array)

## 1D array

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [13]:
x = np.array([1.3, 2.3, 3.4])
print(x)

[1.3 2.3 3.4]


In [14]:
x.dtype

dtype('float64')

### 2D Array

In [16]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [17]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [19]:
x.size

4

In [21]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [22]:
x.shape

(2, 3)

## 3D Array

In [26]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[4, 2, 1],
      [1,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[4, 2, 1],
        [1, 3, 2]]])

In [27]:
x.ndim

3

In [28]:
x.shape

(3, 2, 3)

# Typy danych

In [29]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [30]:
A = np.array([1.0, 2.1, 3.2])
A.dtype

dtype('float64')

In [31]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [32]:
A

array([1., 2., 3.])

In [33]:
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [34]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [35]:
A = np.array([1.0, 2.1, 3.2], dtype='int')
A.dtype

dtype('int64')

In [36]:
A

array([1, 2, 3])

In [37]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [39]:
A = np.array([24, 128, 256], dtype=np.int8)
A.dtype

dtype('int8')