<a href="https://colab.research.google.com/github/yot85/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__


'1.21.6'

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__'

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

## 1D array

In [5]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [12]:
x = np.array([1.3, 2.3, 3.4])
print(x)

[1.3 2.3 3.4]


In [13]:
x.dtype

dtype('float64')

### 2D Array

In [14]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [15]:
x.ndim

2

In [16]:
x.shape

(2, 2)

In [17]:
x.size

4

In [18]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [19]:
x.shape

(2, 3)

## 3D Array

In [20]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[4, 2, 1],
      [1,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[4, 2, 1],
        [1, 3, 2]]])

In [21]:
x.ndim

3

In [22]:
x.shape

(3, 2, 3)

# Typy danych

In [23]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [24]:
A = np.array([1.0, 2.1, 3.2])
A.dtype

dtype('float64')

In [25]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [26]:
A

array([1., 2., 3.])

In [27]:
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [28]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [29]:
A = np.array([1.0, 2.1, 3.2], dtype='int')
A.dtype

dtype('int64')

In [30]:
A

array([1, 2, 3])

In [31]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [32]:
A = np.array([24, 128, 256], dtype=np.int8)
A.dtype

dtype('int8')

# Tworzenie tablic

In [33]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.ones(shape=(5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [40]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [42]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [43]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

'''linspace tworzy tablice o ilości elementów równo rozłożonych w danym przedziale liczb'''

In [44]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

-1 oznacza że nie chcemy sami delfiniować ilości kolumn, chcemy aby NumPy sam dobrał odpowiednią ilość kolumn dla 3 wierszy i 15 elementów w tablicy

In [47]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Podstawowe operacje na tablicach

In [48]:
A = np.array([1, 2, 3, 4])
B = np.array([2, -1, 3,5])
print(A)
print(B)

[1 2 3 4]
[ 2 -1  3  5]


In [49]:
A + B

array([3, 1, 6, 9])

In [50]:
A - B

array([-1,  3,  0, -1])

In [51]:
A * B

array([ 2, -2,  9, 20])

In [52]:
A / B

array([ 0.5, -2. ,  1. ,  0.8])

In [53]:
A + 3

array([4, 5, 6, 7])

In [54]:
A -3

array([-2, -1,  0,  1])

In [55]:
2*A

array([2, 4, 6, 8])

In [56]:
A + 3*B

array([ 7, -1, 12, 19])

In [57]:
np.add(A,B)

array([3, 1, 6, 9])

In [58]:
np.subtract(A,B)

array([-1,  3,  0, -1])

In [59]:
np.multiply(A,B)

array([ 2, -2,  9, 20])

In [60]:
np.divide(A,B)

array([ 0.5, -2. ,  1. ,  0.8])

In [62]:
X = np.array([[-3,1],[2,1]])
Y = np.array([[6,0],[-1,2]])

In [63]:
print(X)
print(Y)

[[-3  1]
 [ 2  1]]
[[ 6  0]
 [-1  2]]


In [64]:
X*Y

array([[-18,   0],
       [ -2,   2]])

In [65]:
np.dot(X,Y)

array([[-19,   2],
       [ 11,   2]])

In [66]:
X.dot(Y)

array([[-19,   2],
       [ 11,   2]])

In [67]:
Y.dot(X)

array([[-18,   6],
       [  7,   1]])

In [68]:
X@Y

array([[-19,   2],
       [ 11,   2]])

znak @ działa tak samo jak funkcja dot - jest to mnożenie macierzowe

# Generowanie liczb pseudolosowych


In [69]:
np.random.seed(0)

In [70]:
np.random.randn()

1.764052345967664

In [71]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [72]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [73]:
np.random.rand()

0.1965823616800535

In [74]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [75]:
np.random.rand(10,2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [77]:
np.random.randint(10)

3

In [78]:
np.random.randint(low=10, high=101)

56

In [79]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [83]:
np.random.choice([1,2,3,4,5,6])

3

In [84]:
np.random.choice(['python','java','sql'])

'sql'

In [88]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.random.shuffle(data)

In [90]:
data

array([7, 2, 1, 6, 0, 5, 9, 3, 4, 8])

# Podstawowe funkcje w bibliotece NumPy


np.exp() - zwraca stałą liczbe Eulera dla przekazanego parametru

In [91]:
np.exp(1)

2.718281828459045

np.sqrt - zwraca pierwiastek kwadratowy dla przekazanej liczby

In [93]:
np.sqrt(4)

2.0

np.all() - przchodzi poprzez elementy listy/macierzy i zwaraca wartośc true lub false w zależności od zawartości

In [96]:
np.all([1,2,0])

False

np.any()  -sprawdza czy w liście/tablicy wystpuje jakakolwiek szukana wartość

In [98]:
np.any([1,1,1,1])

True

In [100]:
A = np.random.rand(5)
A

array([0.88173536, 0.69253159, 0.72525428, 0.50132438, 0.95608363])

In [101]:
np.argmax(A)

4

np.argmax() - zwraca index w którym występuje największa wartość w zbiorze

In [102]:
A[np.argmax(A)]

0.9560836347232239

In [103]:
np.argmin(A)

3

In [104]:
A[np.argmin(A)]

0.5013243819267023

In [105]:
A

array([0.88173536, 0.69253159, 0.72525428, 0.50132438, 0.95608363])

np.argsort() - sortuje wartości i zwaraca indexy 

In [106]:
np.argsort(A)

array([3, 1, 2, 0, 4])

In [107]:
np.max(A)

0.9560836347232239

In [108]:
np.min(A)

0.5013243819267023

In [109]:
np.mean(A)

0.751385849680437

In [110]:
np.median(A)

0.7252542798196405

In [111]:
np.std(A)

0.15847371958621503