<a href="https://colab.research.google.com/github/yot85/data-science-bootcamp/blob/main/02_algerba_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Norma wekrotowa w układzie R^2

In [3]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [4]:
np.linalg.norm(v1)

4.0

Norma euklidesowa w układzie R^n

In [6]:
v2 = np.array([-10, 10, 13])
v2

array([-10,  10,  13])

In [7]:
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [8]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

Odległość dwóch punktów w przestrzeni R^n

In [9]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

Mnożenie macierzy

In [11]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])

print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [12]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [13]:
np.shape(Z)

(2, 1)

In [15]:
X = np.array([[2, -1,3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X)
print(Y)

[[ 2 -1  3]
 [ 3  1  0]]
[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [16]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])